language: node_js
node_js:
  - node
dist: trusty
sudo: false
cache: yarn
branches:
  except: /^feature.*$/
script: yarn run build && yarn run test --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
